### ISSUE TITLE
Package has been archived on CRAN

### ISSUE THREAD

**Issue by Bisaloo** [alxsrobert/measlesoutbreaker#2]
Hi :wave:,

As reported in https://github.com/cran-task-views/Epidemiology/issues/30, o2geosocial has been archived on CRAN for a couple of months now.

Before proceeding with CRAN's request to remove the package from the Epidemiology Task View, I wanted to double check with you the status of this package.

Do you still view this package as stable and useful? If so, would you like support to get it back on CRAN?

**Comment by alxsrobert** [comment]
Hi!

Thank you very much for your message and for bringing this to my attention. It's my mistake, I thought the issues with the package had been fixed and I did not check the CRAN status after the last update. I have re-submitted the package and I'm hoping to get it back on CRAN as soon as possible. I will get in touch if there's any issue with re-submitting.
Thanks again for reaching out!

**Comment by alxsrobert** [comment]
Hi! The package is now back on CRAN (https://cran.r-project.org/web//packages//o2geosocial/index.html), so I'm closing this issue. Thank you very much again for bringing it up, let me know if there's anything else I can help with.
